import {
  type LucideIcon,
  BrainCircuit, Briefcase, Settings, Archive,
  Rss, Users, BookOpen, TrendingUp, Send, ListChecks, Globe,
  Activity, Building2, Landmark, FolderOpen, Leaf,
  Network, Sparkles, LayoutGrid, Languages, ShieldCheck, FileSearch,
  Terminal, ArrowRightLeft, BarChart3, PieChart, Heart, Award,
  Scale, Monitor, MapPin, Megaphone,
  Server, Database, Cloud, Cpu, HardDrive, Wifi,
  Code, GitBranch, Package, Layers, Zap, Bot,
  FileText, Mail, Bell, Lock, Key, Wrench,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  BrainCircuit,
  Briefcase,
  Settings,
  Archive,
  Rss,
  Users,
  BookOpen,
  TrendingUp,
  Send,
  ListChecks,
  Globe,
  Activity,
  Building2,
  Landmark,
  FolderOpen,
  Leaf,
  Network,
  Sparkles,
  LayoutGrid,
  Languages,
  ShieldCheck,
  FileSearch,
  Terminal,
  ArrowRightLeft,
  BarChart3,
  PieChart,
  Heart,
  Award,
  Scale,
  Monitor,
  MapPin,
  Megaphone,
  Server,
  Database,
  Cloud,
  Cpu,
  HardDrive,
  Wifi,
  Code,
  GitBranch,
  Package,
  Layers,
  Zap,
  Bot,
  FileText,
  Mail,
  Bell,
  Lock,
  Key,
  Wrench,
};

export const iconNames = Object.keys(iconMap);

export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? Server;
}
